# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Hard Problems

description: Stylish Jekyll Theme
author:
  name: Chen
  email: cchenhello@gmail.com
  github: endeavorchan
  #twitter: dbtek
 # pinterest: asd123
  #linkedin: asd123
  bio: If you think the problem is hard, please write down your thoughts.
  #email_md5: 726351295ec82e145928582f595aa3aa

#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /Notes
